### ISSUE TITLE
switch to new codecov uploader

### ISSUE THREAD

**Issue by pjfanning** [alejandrohdezma/sbt-codecov#151]
Thanks for writing this plugin.

The bash based codecov uploader is being replaced - https://docs.codecov.com/docs/about-the-codecov-bash-uploader

The new uploader works well.

I have switched to using https://github.com/codecov/codecov-action so I don't need this fix - I'm just logging it as an fyi.

**Comment by alejandrohdezma** [comment]
Hi! Sorry, I don't know why I didn't get a notification for this 😞

Given that the GitHub Action is in a much more mature state right now, I think I'll be archiving/deprecating this plugin.

Thanks!
